# Default values for left-food-api.
# This is a YAML-formatted file.
# Declare variables that are passed into your templates.

replicaCount: 1

image:
  repository: left-food-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

service:
  type: ClusterIP
  # The port the Service will expose
  port: 8085
  # The port on the container that the Service will target
  targetPort: 8085

# Non-sensitive configuration that will be stored in a ConfigMap
config:
  # The Spring profile to activate. This should match your application-kubernetes.yaml
  springProfile: "kubernetes"
  # For Docker Desktop, 'host.docker.internal' points to your local machine.
  # This connects to Keycloak running on your localhost:8080.
  jwtIssuerUri: "http://host.docker.internal:8080/realms/my-app-realm"
  # This connects to PostgreSQL running on your localhost:5432.
  databaseUrl: "jdbc:postgresql://host.docker.internal:5432/my-food-db"

# Sensitive configuration that will be stored in a Kubernetes Secret.
# It's highly recommended to manage these values outside of version control,
# for example, by using --set or a separate values file during helm install.
secrets:
  databaseUser: "postgres" # Default user for dev
  databasePassword: "admin" # Default password for dev, MUST be overridden for prod

# Resource requests and limits for the application pod
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Liveness and Readiness probes for the application pod.
# Spring Boot Actuator provides these endpoints out-of-the-box.
probes:
  liveness:
    enabled: true
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    enabled: true
    path: /actuator/health/readiness
    initialDelaySeconds: 15
    periodSeconds: 5
