# Default values for ipic-service-discovery.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP
  port: 8761 # The service port

image:
  repository: cgurugc/service-discovery
  tag: "latest" # This will be overridden by the Jenkins pipeline